# Librarian

Librarian gives Laravel projects a strict documentation structure for keeping
product intent, code, and tests aligned.

## Documentation Spine

Projects using Librarian should maintain this docs structure:

```text
docs/
  README.md
  mission.md
  architecture.md
  tech-stack.md
  concepts.md
  domains/
```

`docs/README.md` and `docs/concepts.md` are generated by Librarian and should
not be hand-edited. Put project-specific prose in `mission.md`,
`architecture.md`, `tech-stack.md`, and domain files below `docs/domains`.

## Commands

Use Librarian's Artisan commands instead of manually creating or reshuffling the
docs spine:

```bash
php artisan librarian:init
php artisan librarian:domain billing
php artisan librarian:domains:normalize
php artisan librarian:build
php artisan librarian:lint
```

Use `librarian:build` after changing docs that affect generated indexes. Use
`librarian:lint` as the read-only consistency check in CI.

## Writing Librarian Docs

- Write concrete product intent, not generic template filler.
- Keep mission, architecture, tech stack, and domain docs aligned with code and
  tests.
- Use lowercase kebab-case domain slugs.
- Prefer local markdown links that resolve inside the docs tree.
- Remove scaffold prompt text once the project has real content.
